title: "Unreal Engine Documentation"
description: "Comprehensive guide for Unreal Engine components and systems."
remote_theme: pmarsceill/just-the-docs # Uses the 'Just the Docs' theme
markdown: kramdown
permalink: /:path/

just_the_docs:
  # Navigation settings
  navigation:
    - name: "Home"
      url: "/Unreal/"
    - name: "Getting Started"
      url: "/docs/getting-started"
    - name: "Health Component"
      url: "/docs/health-component"

# Optional GitHub repo info
repository: "arturg04/unreal-documentation"
