title: Unreal Engine Documentation
description: Documentation for Unreal Engine systems and components."
theme: just-the-docs

# Sidebar and navigation configuration
just_the_docs:
  show_sidebar: true
  navigation:
    - name: "Getting Started"
      url: "/docs/getting-started"
    - name: "Health Component"
      url: "/docs/health-component"