title: "Unreal Engine Documentation"
description: "Documentation for Unreal Engine systems and components."
repository: just-the-docs/just-the-docs
markdown: kramdown

# Navigation settings
just_the_docs:
  show_sidebar: true
  navigation:
    - name: "Getting Started"
      url: "/docs/getting-started"
    - name: "Health Component"
      url: "/docs/health-component"