name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Run on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Ensure this version matches Jekyll requirements
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Build the site
      run: |
        bundle exec jekyll build --destination _site

    - name: Upload site to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: _site

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
